# Use an official NGINX runtime as a parent image
FROM nginx:alpine

# Copy the frontend files to the NGINX html directory
COPY index.html /usr/share/nginx/html

# Make port 80 available to the world outside this container
EXPOSE 80
